export const Characters = [
  {
    id: "bardock",
    name: "Bardock",
    description: "Goku's dad",
    type: "h",
  },
  {
    id: "gohan",
    name: "Gohan",
    description: "Goku's eldest son",
    type: "h",
  },
  {
    id: "goku",
    name: "Goku",
    description: "Protagonist of DB",
    type: "h",
  },
  {
    id: "krillin",
    name: "Krillin",
    description: "Goku's best friend",
    type: "h",
  },
  {
    id: "majin_buu",
    name: "Majin Buu",
    description: "Enemy in DB",
    type: "h",
  },
  {
    id: "super_buu",
    name: "Super Majin Buu",
    description: "Enemy in DB",
    type: "h",
  },
  {
    id: "evil_buu",
    name: "Evil Majin Buu",
    description: "Enemy in DB",
    type: "h",
  },
  {
    id: "kid_buu",
    name: "Kid Majin Buu",
    description: "Enemy in DB",
    type: "h",
  },
  {
    id: "piccolo",
    name: "Piccolo",
    description: "Enemy and later friend of Goku",
    type: "h",
  },
  {
    id: "vegeta",
    name: "Vegeta",
    description: "Prince of the Saiyans",
    type: "h",
  },
  {
    id: "bulma",
    name: "Bulma",
    description: "Vegeta's wife",
    type: "m",
  },
  {
    id: "caulifla",
    name: "Caulifla",
    description: "Saiyajin from another universe",
    type: "m",
  },
  {
    id: "gine",
    name: "Gine",
    description: "Goku's mom",
    type: "m",
  },
  {
    id: "milk",
    name: "Milk",
    description: "Goku's wife",
    type: "m",
  },
  {
    id: "no18",
    name: "Androide No. 18",
    description: "Krillin's wife",
    type: "m",
  },
  {
    id: "vados",
    name: "Vados",
    description: "Angel of the god of destruction Champa",
    type: "m",
  },
  {
    id: "videl",
    name: "Videl",
    description: "Gohan's wife",
    type: "m",
  },
];
